//getting user details 
export const LOAD_PRODUCT_DETAILS_START = 'LOAD_PRODUCT_DETAILS_START';
export const LOAD_PRODUCT_DETAILS_SUCCESS = 'LOAD_PRODUCT_DETAILS_SUCCESS';
export const LOAD_PRODUCT_DETAILS_ERROR = 'LOAD_PRODUCT_DETAILS_ERROR';


 