//getting user details 
export const LOAD_USERS_DETAILS_START = 'LOAD_USERS_DETAILS_START';
export const LOAD_USERS_DETAILS_SUCCESS = 'LOAD_USERS_DETAILS_SUCCESS';
export const LOAD_USERS_DETAILS_ERROR = 'LOAD_USERS_DETAILS_ERROR';


 